npc_generator/urls.py
from django.urls import path, re_path

from . import views

app_name = 'npc_generator'
urlpatterns = [
    path('', views.index, name='index'),
    path('results', views.results, name='results')
]

npc_generator_website/urls.py
from django.urls import include, path
from django.contrib import admin
from .views import redirect_root

urlpatterns = [
    path(('npc_generator/'), include('npc_generator.urls')),
    path('admin/', admin.site.urls),
    path('', redirect_root),
]

npc_generator/models.py
from django.db import models

# Create your models here.


class WeaponProficiencyList(models.Model):
    char_list_name = models.CharField(max_length=50)

    def __str__(self):
        return self.char_list_name


class Weapon(models.Model):
    weapon_name = models.CharField(max_length=20)
    SIMPLE_WEAPON = 0
    MARTIAL_WEAPON = 1
    EXOTIC_WEAPON = 2
    weapon_types_list = (
        (SIMPLE_WEAPON, 'Simple'),
        (MARTIAL_WEAPON, 'Martial'),
        (EXOTIC_WEAPON, 'Exotic'),
    )
    MELEE = 0
    RANGED = 1
    WEAPON_MEL_RANGE_LIST = (
        (MELEE, 'melee'),
        (RANGED, 'ranged'),
    )
    weapon_type = models.IntegerField(choices=weapon_types_list)
    weapon_mel_range = models.IntegerField(choices=WEAPON_MEL_RANGE_LIST)
    weapon_damage = models.CharField(max_length=10)
    weapon_crit = models.CharField(max_length = 10)
    weapon_hands = models.PositiveSmallIntegerField()
    weapon_range = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.weapon_name


class ListedWeapon(models.Model):
    proficiency_list = models.ForeignKey(WeaponProficiencyList, on_delete=models.CASCADE)
    weapon = models.ForeignKey(Weapon, on_delete=models.CASCADE)
    damage = Weapon.weapon_damage
    w_list_name = models.CharField(max_length=20)

    def __str__(self):
        return self.w_list_name


class ArmourProficiencyList(models.Model):
    armour_list_name = models.CharField(max_length=20)

    def __str__(self):
        return self.armour_list_name


class Armour(models.Model):
    armour_name = models.CharField(max_length=20)
    LIGHT_ARMOUR = 0
    MEDIUM_ARMOUR = 1
    HEAVY_ARMOUR = 2
    ARMOUR_TYPE_CHOICES = (
        (LIGHT_ARMOUR, 'light'),
        (MEDIUM_ARMOUR, 'medium'),
        (HEAVY_ARMOUR, 'heavy'),
    )
    armour_type = models.IntegerField(choices=ARMOUR_TYPE_CHOICES)
    armour_ac = models.PositiveSmallIntegerField()
    armour_max_dex = models.IntegerField()

    def __str__(self):
        return self.armour_name

class ListedArmour(models.Model):
    proficiency_list = models.ForeignKey(ArmourProficiencyList, on_delete=models.CASCADE)
    armour = models.ForeignKey(Armour, on_delete=models.CASCADE)
    a_list_name = models.CharField(max_length=20)
    def __str__(self):
        return self.a_list_name


class CharClass(models.Model):
    name = models.CharField(max_length=20) # Name of character class
    hit_dice = models.PositiveSmallIntegerField() # Dice to roll when determining HP
    base_attack = models.FloatField()   #Character's base attack
    fort_save_ratio = models.CharField(max_length=10) #A word describing how the character's saves scale with their level
    reflex_save_ratio = models.CharField(max_length=10)
    will_save_ratio = models.CharField(max_length=10)
    STR = 1 # Defining the set of choices for top 3 ability scores
    DEX = 2
    CON = 3
    INT = 4
    WIS = 5
    CHA = 6
    ABILITY_CHOICES = (
        (STR, 'Strength'),
        (DEX, 'Dexterity'),
        (CON, 'Constitution'),
        (INT, 'Intelligence'),
        (WIS, 'Wisdom'),
        (CHA, 'Charisma'),
    )
    primary_ability = models.IntegerField(choices=ABILITY_CHOICES)
    secondary_ability = models.IntegerField(choices=ABILITY_CHOICES)
    tertiary_ability = models.IntegerField(choices=ABILITY_CHOICES)
    weapon_proficiencies = models.ForeignKey(WeaponProficiencyList, on_delete=models.PROTECT)
    armour_proficiencies = models.ForeignKey(ArmourProficiencyList, on_delete=models.PROTECT)

    def __str__(self):
        return self.name

npc_generator/forms.py
from django import forms
from .models import CharClass

class CharForm(forms.Form):
    char_class = forms.ModelChoiceField(label="What character class would you like?", queryset=CharClass.objects.all())
    level = forms.IntegerField(label="What level should they be?", min_value=1, max_value=20, initial=1)
    num_char = forms.IntegerField(label="How many characters would you like to generate?", min_value=1, max_value=10, initial=5)

npc_generator/views.py
from .forms import CharForm
from .models import CharClass
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .npc_generator import character_generator

def index(request):
    if request.method == 'POST':
        form = CharForm(request.POST)
        if form.is_valid():
            char_class = form.cleaned_data['char_class']
            level = form.cleaned_data['level']
            num_char = form.cleaned_data['num_chars']
            return HttpResponseRedirect('/results/')

    else:
        form = CharForm()

    return render(request, 'npc_generator/index.html', {'form': form})


def results(request):
    char_class = request.POST['char_class']
    char_class = CharClass.objects.get(pk=char_class)
    level = int(request.POST['level'])
    num_char = int(request.POST['num_char'])
    characters = []
    for i in range(num_char):
        character = character_generator(char_class, level)
        characters.append(character)
    return render(request, 'npc_generator/results.html', {'characters': characters})

npc_generator_website/views.py
from django.http import HttpResponseRedirect

def redirect_root(request):
    return HttpResponseRedirect('/npc_generator/')

npc_generator/templates/npc_generator/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>D&D 3.5 NPC Generator</h2>
    <p>This is an NPC generator for D&D 3.5 Edition. Please use the form below to choose the level, class and number
        of characters you want to generate.</p>
    <p>As the NPCs are randomised, it is recommended that you generate more than one so that you can choose your favourite.</p>
    <form action="{% url 'npc_generator:results' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

npc_generator/templates/npc_generator/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NPC Generator</title>
</head>
<body>
    <h2>D&D 3.5 NPC Generator</h2>
    <a href="javascript:window.location.reload(true)">Generate again.</a>
    <a href="{% url 'npc_generator:index' %}">Generate new characters.</a>
{% if characters %}
    {% for character in characters %}
        <h4>Level {{ character.level }} {{ character.name }}</h4>
        <p>HP: {{ character.hp }} AC: {{ character.ac }} Armour: {{character.armour}}</p>
        <p>Abilities: STR: {{character.str}}, DEX: {{character.dex}}, CON: {{character.con }}, INT: {{character.int}},
            WIS: {{character.wis}}, CHA: {{character.cha}}</p>
        <p>Base attack: +{{ character.base_attack }}, Melee attack: +{{ character.melee_attack }} ({{ character.melee_weapon.weapon_name }}
            {{ character.melee_weapon.weapon_damage }}+{{ character.str_mod }}), Ranged attack: +{{ character.ranged_attack }}
         ({{character.ranged_weapon.weapon_name }} {{ character.ranged_weapon.weapon_damage}})</p>
        <p>Saves: F/R/W +{{character.fort_save}}/+{{character.reflex_save}}/+{{character.will_save}}</p>
    {% endfor %}
{% endif %}
</body>
</html>